# OmicIDX
#
#     The OmicIDX API documentation is available in three forms:  - [RapiDoc](/docs) - [OpenAPI/Swagger Interactive](/swaggerdoc) - [ReDoc (more readable in some ways)](/redoc)  
#
# OpenAPI spec version: 0.99.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' HTTPValidationError Class
#'
#' @field detail Detail
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HTTPValidationError <- R6::R6Class(
  'HTTPValidationError',
  public = list(
    `detail` = NULL,
    initialize = function(`detail`){
      if (!missing(`detail`)) {
        stopifnot(is.list(`detail`), length(`detail`) != 0)
        lapply(`detail`, function(x) stopifnot(R6::is.R6(x)))
        self$`detail` <- `detail`
      }
    },
    toJSON = function() {
      HTTPValidationErrorObject <- list()
      if (!is.null(self$`detail`)) {
        HTTPValidationErrorObject[['detail']] <- lapply(self$`detail`, function(x) x$toJSON())
      }

      HTTPValidationErrorObject
    },
    fromJSON = function(HTTPValidationErrorJson) {
      HTTPValidationErrorObject <- jsonlite::fromJSON(HTTPValidationErrorJson)
      if (!is.null(HTTPValidationErrorObject$`detail`)) {
        self$`detail` <- lapply(HTTPValidationErrorObject$`detail`, function(x) {
          detailObject <- ValidationError$new()
          detailObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          detailObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "detail": [%s]
        }',
        lapply(self$`detail`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(HTTPValidationErrorJson) {
      HTTPValidationErrorObject <- jsonlite::fromJSON(HTTPValidationErrorJson)
      self$`detail` <- lapply(HTTPValidationErrorObject$`detail`, function(x) ValidationError$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
