# OmicIDX
#
#     The OmicIDX API documentation is available in three forms:  - [RapiDoc](/docs) - [OpenAPI/Swagger Interactive](/swaggerdoc) - [ReDoc (more readable in some ways)](/redoc)  
#
# OpenAPI spec version: 0.99.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ResponseModel Class
#'
#' @field hits Hits
#' @field facets Facets
#' @field stats 
#' @field success Success
#' @field cursor Cursor
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ResponseModel <- R6::R6Class(
  'ResponseModel',
  public = list(
    `hits` = NULL,
    `facets` = NULL,
    `stats` = NULL,
    `success` = NULL,
    `cursor` = NULL,
    initialize = function(`hits`, `facets`, `stats`, `success`, `cursor`){
      if (!missing(`hits`)) {
        stopifnot(is.list(`hits`), length(`hits`) != 0)
        lapply(`hits`, function(x) stopifnot(R6::is.R6(x)))
        self$`hits` <- `hits`
      }
      if (!missing(`facets`)) {
        stopifnot(is.list(`facets`), length(`facets`) != 0)
        lapply(`facets`, function(x) stopifnot(R6::is.R6(x)))
        self$`facets` <- `facets`
      }
      if (!missing(`stats`)) {
        stopifnot(R6::is.R6(`stats`))
        self$`stats` <- `stats`
      }
      if (!missing(`success`)) {
        self$`success` <- `success`
      }
      if (!missing(`cursor`)) {
        stopifnot(is.character(`cursor`), length(`cursor`) == 1)
        self$`cursor` <- `cursor`
      }
    },
    toJSON = function() {
      ResponseModelObject <- list()
      if (!is.null(self$`hits`)) {
        ResponseModelObject[['hits']] <- lapply(self$`hits`, function(x) x$toJSON())
      }
      if (!is.null(self$`facets`)) {
        ResponseModelObject[['facets']] <- lapply(self$`facets`, function(x) x$toJSON())
      }
      if (!is.null(self$`stats`)) {
        ResponseModelObject[['stats']] <- self$`stats`$toJSON()
      }
      if (!is.null(self$`success`)) {
        ResponseModelObject[['success']] <- self$`success`
      }
      if (!is.null(self$`cursor`)) {
        ResponseModelObject[['cursor']] <- self$`cursor`
      }

      ResponseModelObject
    },
    fromJSON = function(ResponseModelJson) {
      ResponseModelObject <- jsonlite::fromJSON(ResponseModelJson)
      if (!is.null(ResponseModelObject$`hits`)) {
        self$`hits` <- ResponseModelObject$`hits`
      }
      if (!is.null(ResponseModelObject$`facets`)) {
        self$`facets` <- ResponseModelObject$`facets`
      }
      if (!is.null(ResponseModelObject$`stats`)) {
        statsObject <- ResponseStats$new()
        statsObject$fromJSON(jsonlite::toJSON(ResponseModelObject$stats, auto_unbox = TRUE))
        self$`stats` <- statsObject
      }
      if (!is.null(ResponseModelObject$`success`)) {
        self$`success` <- ResponseModelObject$`success`
      }
      if (!is.null(ResponseModelObject$`cursor`)) {
        self$`cursor` <- ResponseModelObject$`cursor`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "hits": [%s],
           "facets": [%s],
           "stats": %s,
           "success": %s,
           "cursor": %s
        }',
        lapply(self$`hits`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`facets`, function(x) paste(x$toJSON(), sep=",")),
        self$`stats`$toJSON(),
        self$`success`,
        self$`cursor`
      )
    },
    fromJSONString = function(ResponseModelJson) {
      ResponseModelObject <- jsonlite::fromJSON(ResponseModelJson)
      self$`hits` <- ResponseModelObject$`hits`
      self$`facets` <- ResponseModelObject$`facets`
      ResponseStatsObject <- ResponseStats$new()
      self$`stats` <- ResponseStatsObject$fromJSON(jsonlite::toJSON(ResponseModelObject$stats, auto_unbox = TRUE))
      self$`success` <- ResponseModelObject$`success`
      self$`cursor` <- ResponseModelObject$`cursor`
    }
  )
)
