# OmicIDX
#
#     The OmicIDX API documentation is available in three forms:  - [RapiDoc](/docs) - [OpenAPI/Swagger Interactive](/swaggerdoc) - [ReDoc (more readable in some ways)](/redoc)  
#
# OpenAPI spec version: 0.99.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ResponseStats Class
#'
#' @field total Total
#' @field took Took
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ResponseStats <- R6::R6Class(
  'ResponseStats',
  public = list(
    `total` = NULL,
    `took` = NULL,
    initialize = function(`total`, `took`){
      if (!missing(`total`)) {
        stopifnot(is.numeric(`total`), length(`total`) == 1)
        self$`total` <- `total`
      }
      if (!missing(`took`)) {
        stopifnot(is.numeric(`took`), length(`took`) == 1)
        stopifnot(R6::is.R6(`took`))
        self$`took` <- `took`
      }
    },
    toJSON = function() {
      ResponseStatsObject <- list()
      if (!is.null(self$`total`)) {
        ResponseStatsObject[['total']] <- self$`total`
      }
      if (!is.null(self$`took`)) {
        ResponseStatsObject[['took']] <- self$`took`$toJSON()
      }

      ResponseStatsObject
    },
    fromJSON = function(ResponseStatsJson) {
      ResponseStatsObject <- jsonlite::fromJSON(ResponseStatsJson)
      if (!is.null(ResponseStatsObject$`total`)) {
        self$`total` <- ResponseStatsObject$`total`
      }
      if (!is.null(ResponseStatsObject$`took`)) {
        self$`took` <- fromJSON(jsonlite::toJSON(ResponseStatsObject$took, auto_unbox = TRUE))
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "total": %d,
           "took": %s
        }',
        self$`total`,
        self$`took`)
    },
    fromJSONString = function(ResponseStatsJson) {
      ResponseStatsObject <- jsonlite::fromJSON(ResponseStatsJson)
      self$`total` <- ResponseStatsObject$`total`
      self$`took` <- fromJSON(jsonlite::toJSON(ResponseStatsObject$took, auto_unbox = TRUE))
    }
  )
)
