# OmicIDX
#
#     The OmicIDX API documentation is available in three forms:  - [RapiDoc](/docs) - [OpenAPI/Swagger Interactive](/swaggerdoc) - [ReDoc (more readable in some ways)](/redoc)  
#
# OpenAPI spec version: 0.99.1
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#' @title SRA operations
#' @description swagger.SRA
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' experiment_by_accession_sra_experiments_accession_get Experiment By Accession
#'
#'
#' experiments_for_sample_sra_samples_accession_experiments_get Experiments For Sample
#'
#'
#' experiments_for_study_sra_studies_accession_experiments_get Experiments For Study
#'
#'
#' experiments_sra_experiments_get Experiments
#'
#'
#' mapping_sra_fields_entity_get Mapping
#'
#'
#' run_by_accession_sra_runs_accession_get Run By Accession
#'
#'
#' runs_for_experiment_sra_experiments_accession_runs_get Runs For Experiment
#'
#'
#' runs_for_sample_sra_samples_accession_runs_get Runs For Sample
#'
#'
#' runs_for_study_sra_studies_accession_runs_get Runs For Study
#'
#'
#' runs_sra_runs_get Runs
#'
#'
#' sample_by_accession_sra_samples_accession_get Sample By Accession
#'
#'
#' samples_for_study_sra_studies_accession_samples_get Samples For Study
#'
#'
#' samples_sra_samples_get Samples
#'
#'
#' studies_sra_studies_get Studies
#'
#'
#' study_by_accession_sra_studies_accession_get Study By Accession
#'
#' }
#'
#' @export
SRAApi <- R6::R6Class(
  'SRAApi',
  public = list(
    userAgent = "Swagger-Codegen/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    experiment_by_accession_sra_experiments_accession_get = function(accession, include_fields, exclude_fields, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      urlPath <- "/sra/experiments/{accession}"
      if (!missing(`accession`)) {
        urlPath <- gsub(paste0("\\{", "accession", "\\}"), `accession`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Object$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    experiments_for_sample_sra_samples_accession_experiments_get = function(accession, include_fields, exclude_fields, size, cursor, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      if (!missing(`size`)) {
        queryParams['size'] <- size
      }

      if (!missing(`cursor`)) {
        queryParams['cursor'] <- cursor
      }

      urlPath <- "/sra/samples/{accession}/experiments"
      if (!missing(`accession`)) {
        urlPath <- gsub(paste0("\\{", "accession", "\\}"), `accession`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Object$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    experiments_for_study_sra_studies_accession_experiments_get = function(accession, include_fields, exclude_fields, size, cursor, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      if (!missing(`size`)) {
        queryParams['size'] <- size
      }

      if (!missing(`cursor`)) {
        queryParams['cursor'] <- cursor
      }

      urlPath <- "/sra/studies/{accession}/experiments"
      if (!missing(`accession`)) {
        urlPath <- gsub(paste0("\\{", "accession", "\\}"), `accession`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Object$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    experiments_sra_experiments_get = function(q, size, cursor, facet_size, include_fields, exclude_fields, facets, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`q`)) {
        queryParams['q'] <- q
      }

      if (!missing(`size`)) {
        queryParams['size'] <- size
      }

      if (!missing(`cursor`)) {
        queryParams['cursor'] <- cursor
      }

      if (!missing(`facet_size`)) {
        queryParams['facet_size'] <- facet_size
      }

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      if (!missing(`facets`)) {
        queryParams['facets'] <- facets
      }

      urlPath <- "/sra/experiments"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- ResponseModel$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    mapping_sra_fields_entity_get = function(entity, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      urlPath <- "/sra/fields/{entity}"
      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), `entity`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Object$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    run_by_accession_sra_runs_accession_get = function(accession, include_fields, exclude_fields, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      urlPath <- "/sra/runs/{accession}"
      if (!missing(`accession`)) {
        urlPath <- gsub(paste0("\\{", "accession", "\\}"), `accession`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Object$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    runs_for_experiment_sra_experiments_accession_runs_get = function(accession, include_fields, exclude_fields, size, cursor, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      if (!missing(`size`)) {
        queryParams['size'] <- size
      }

      if (!missing(`cursor`)) {
        queryParams['cursor'] <- cursor
      }

      urlPath <- "/sra/experiments/{accession}/runs"
      if (!missing(`accession`)) {
        urlPath <- gsub(paste0("\\{", "accession", "\\}"), `accession`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Object$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    runs_for_sample_sra_samples_accession_runs_get = function(accession, include_fields, exclude_fields, size, cursor, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      if (!missing(`size`)) {
        queryParams['size'] <- size
      }

      if (!missing(`cursor`)) {
        queryParams['cursor'] <- cursor
      }

      urlPath <- "/sra/samples/{accession}/runs"
      if (!missing(`accession`)) {
        urlPath <- gsub(paste0("\\{", "accession", "\\}"), `accession`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Object$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    runs_for_study_sra_studies_accession_runs_get = function(accession, include_fields, exclude_fields, size, cursor, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      if (!missing(`size`)) {
        queryParams['size'] <- size
      }

      if (!missing(`cursor`)) {
        queryParams['cursor'] <- cursor
      }

      urlPath <- "/sra/studies/{accession}/runs"
      if (!missing(`accession`)) {
        urlPath <- gsub(paste0("\\{", "accession", "\\}"), `accession`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Object$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    runs_sra_runs_get = function(q, size, cursor, facet_size, include_fields, exclude_fields, facets, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`q`)) {
        queryParams['q'] <- q
      }

      if (!missing(`size`)) {
        queryParams['size'] <- size
      }

      if (!missing(`cursor`)) {
        queryParams['cursor'] <- cursor
      }

      if (!missing(`facet_size`)) {
        queryParams['facet_size'] <- facet_size
      }

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      if (!missing(`facets`)) {
        queryParams['facets'] <- facets
      }

      urlPath <- "/sra/runs"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- ResponseModel$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    sample_by_accession_sra_samples_accession_get = function(accession, include_fields, exclude_fields, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      urlPath <- "/sra/samples/{accession}"
      if (!missing(`accession`)) {
        urlPath <- gsub(paste0("\\{", "accession", "\\}"), `accession`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Object$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    samples_for_study_sra_studies_accession_samples_get = function(accession, include_fields, exclude_fields, size, cursor, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      if (!missing(`size`)) {
        queryParams['size'] <- size
      }

      if (!missing(`cursor`)) {
        queryParams['cursor'] <- cursor
      }

      urlPath <- "/sra/studies/{accession}/samples"
      if (!missing(`accession`)) {
        urlPath <- gsub(paste0("\\{", "accession", "\\}"), `accession`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Object$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    samples_sra_samples_get = function(q, size, cursor, facet_size, include_fields, exclude_fields, facets, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`q`)) {
        queryParams['q'] <- q
      }

      if (!missing(`size`)) {
        queryParams['size'] <- size
      }

      if (!missing(`cursor`)) {
        queryParams['cursor'] <- cursor
      }

      if (!missing(`facet_size`)) {
        queryParams['facet_size'] <- facet_size
      }

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      if (!missing(`facets`)) {
        queryParams['facets'] <- facets
      }

      urlPath <- "/sra/samples"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- ResponseModel$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    studies_sra_studies_get = function(q, size, cursor, facet_size, include_fields, exclude_fields, facets, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`q`)) {
        queryParams['q'] <- q
      }

      if (!missing(`size`)) {
        queryParams['size'] <- size
      }

      if (!missing(`cursor`)) {
        queryParams['cursor'] <- cursor
      }

      if (!missing(`facet_size`)) {
        queryParams['facet_size'] <- facet_size
      }

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      if (!missing(`facets`)) {
        queryParams['facets'] <- facets
      }

      urlPath <- "/sra/studies"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- ResponseModel$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    },
    study_by_accession_sra_studies_accession_get = function(accession, include_fields, exclude_fields, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`include_fields`)) {
        queryParams['include_fields'] <- include_fields
      }

      if (!missing(`exclude_fields`)) {
        queryParams['exclude_fields'] <- exclude_fields
      }

      urlPath <- "/sra/studies/{accession}"
      if (!missing(`accession`)) {
        urlPath <- gsub(paste0("\\{", "accession", "\\}"), `accession`, urlPath)
      }

      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- Object$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
